import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
<<<<<<< HEAD
=======
import Navbar from "@/component/layout/Navbar";
import Footer from "@/component/layout/Footer";
import { GlobalStateProvider } from "@/contexts/GlobalStateContext";
>>>>>>> 2fccccab0f6ab0a026c1827b3855f24e03d6bf8e
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Euis Siti Meida",
=======
  title: "Muhammad Hafidz Alghifari",
>>>>>>> 2fccccab0f6ab0a026c1827b3855f24e03d6bf8e
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalStateProvider>
          <Navbar />
          {children}
          <Footer />
        </GlobalStateProvider>
      </body>
    </html>
  );
}
